---
format:
    html:
        embed-rmd: true
        output-ext: "htm"
---

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}

if (file.exists("renv.lock")){
    renv::restore(prompt = FALSE)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

```

<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r partB_retrieve_reference_gene_sets_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "B2.ref.gmt."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

```


### Load Reference Gene Sets
```{r partB_create_sample_list, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Load reference datasets                                                   ##


Obio@dataTableList[["referenceList"]] <- NULL

if (!is.null(Obio@dbDetailList$host)){
  
    if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol" 
  } else {
            queryGS <- Obio@parameterList$geneIDcolumn
  }
  
    Obio@dataTableList[["referenceList"]] <- list(
        "s.genes" = retrieve.gene.category.from.db(
                        cat_id = "ag_lab_categories__41",
                        password = db.pwd,
                        gene.symbol = queryGS,
                        user = Obio@dbDetailList$db.user,
                        host = Obio@dbDetailList$host
                    ),
        "g2m.genes" = retrieve.gene.category.from.db(
                          cat_id = "ag_lab_categories__42",
                          password = db.pwd,
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    ),
        "TFs" = retrieve.gene.category.from.db(
                          cat_id = "ag_lab_categories__10",
                          password = db.pwd,
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    )
        
      )
}




## Done create cellRanger QC plots                                           ##
###############################################################################


```

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

if (exists("whiteListWorkspace")){
    rmVec <- ls()[!(ls() %in% whiteListWorkspace)]
    rm(list = rmVec)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```

