---
format:
    html:
        embed-rmd: true
        output-ext: "htm"
---

## Dotplot Chapter
```{r, eval=T, echo=F, results=FALSE, message = FALSE, warning = FALSE}
if (file.exists("renv.lock")){
    renv::restore(prompt = FALSE)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

library(dplyr)
```

<!-- Set PArameters Module -->
<!-- Set the chnkPrefix to make all chunks unique in the overall folder -->
```{r partB_create_dot_init, echo=TRUE, eval=TRUE, warning=FALSE}
chnkPrefix <- "Dot."
VersionPdfExt <- VersionPdfExt <- paste0(".",chnkPrefix,"V", gsub("-", "", Sys.Date()), ".pdf")

# Load specific version of R
#module purge;source /camp/stp/babs/working/software/modulepath_new_software_tree_2018-08-13;module load pandoc/2.2.3.2-foss-2016b;ml R/4.0.3-foss-2020a
```

```{r dotplot_prep, echo=TRUE, eval=TRUE, warning=FALSE, results=F}
###############################################################################
## Do percent mt plots

###############################################################################
## Depending on the project, another parameter can be used for heatmap       ##
## segmentation. The default is cluster_sampleName

segmentationCol <- "sampleName"

## Add column for averaging of cells
selClust <- paste0("clusterName_", segmentationCol)
OsC_HM <- OsC
OsC_HM@meta.data[[selClust]] <- paste0(
  OsC_HM@meta.data$clusterName,
  "_",
  OsC_HM@meta.data[,segmentationCol]
)

###############################################################################
## Calculataing average across segmentation                                  ##
Seurat::Idents(OsC_HM) <- selClust
OsCsel <- Seurat::AverageExpression(
  OsC_HM,
  return.seurat = TRUE
)


if (segmentationCol == "sampleName" & length(grep("^sampleColor$", names(OsC_HM@meta.data)) == 1)){
  segmentationColorCol <- "sampleColor"
} else{
  segmentationColorCol <- paste0(
    segmentationCol,
    "Color"
  )

  ## Colors can also be set manually here
  allCols <- unique(OsC_HM@meta.data[,segmentationCol])
  colorSel <- scales::hue_pal()(length(allCols))

  OsC_HM@meta.data[[segmentationColorCol]] <- OsC_HM@meta.data[[segmentationCol]]
  for (i in 1:length(allCols)){
    OsC_HM@meta.data[[segmentationColorCol]] <- gsub(
      allCols[i],
      colorSel[i],
      OsC_HM@meta.data[[segmentationColorCol]]

    )
  }

} # done with else of if clause



selVec <- c(
  "clusterName",
  "clusterColor",
  segmentationCol,
  segmentationColorCol,
  selClust
)

dfAdd <- unique(OsC_HM@meta.data[,selVec])

## Add color vector for segmentationCol ##

#dfAdd[["treatmentGroupColor"]] <- dfAdd$meta_Treatment
#dfAdd$treatmentGroupColor <- gsub("Control", "#3B5EF7", dfAdd$treatmentGroupColor)
#dfAdd$treatmentGroupColor <- gsub("MatB52", "#4DA868", dfAdd$treatmentGroupColor)
#dfAdd$treatmentGroupColor <- gsub("Regeneron", "#EE6C58", dfAdd$treatmentGroupColor)

row.names(dfAdd) <- gsub("_", "-", dfAdd[,selClust])

OsCsel <- biologicToolsSC::addDf2seuratMetaData(
  obj = OsCsel,
  dfAdd = dfAdd
)

## Order of factors
if (is.null(Obio@parameterList$clusterNameOrder)){
    Obio@parameterList$clusterNameOrder <- sort(unique(OsC@meta.data$clusterName))
}

segmentationColOrder <- sort(unique(OsCsel@meta.data[[segmentationCol]]))

if (segmentationCol == "sampleName" & !is.null(Obio@parameterList$sampleNameOrder)){
  segmentationColOrder <- Obio@parameterList$sampleNameOrder
}

OsCsel@meta.data[[segmentationCol]] <- factor(
  OsCsel@meta.data[[segmentationCol]],
  levels = segmentationColOrder
)

OsCsel@meta.data$clusterName <- factor(
  OsCsel@meta.data$clusterName,
  levels=Obio@parameterList$clusterNameOrder
)


OsCsel@meta.data <- OsCsel@meta.data[order(OsCsel@meta.data$clusterName,OsCsel@meta.data[[segmentationCol]]),]

dfData <- data.frame(OsCsel@assays$RNA$data)

names(dfData) <- gsub("\\.", "-", names(dfData))

dataMatrix <- data.matrix(dfData)
dfMeta <- OsCsel@meta.data

dataMatrix <- dataMatrix[,gsub("_", "-", dfMeta[,selClust])]


HMgeneSelections <- list()

## Cluster markers

## Start with LR
LRgeneList <- list()
topNselection <- 3

dfTemp <-  Obio@dataTableList$dfClusterResiduals

clusterNames <- unique( Obio@parameterList$clusterNameOrder)

for (i in 1:length(clusterNames)){
  dfTemp <- dfTemp[order(dfTemp[, clusterNames[i]], decreasing = T), ]

  if (topNselection > nrow(dfTemp)){
      topNselection <- nrow(dfTemp)
  }

  geneVec <- as.vector(sort(dfTemp[1:topNselection, "gene"]))

  LRgeneList[[clusterNames[i]]] <- geneVec
}

HMgeneSelections[["LR_Markers"]] <- LRgeneList

## Add LR_TF markers

## Get transcription factor genes ##
if (dir.exists("/Volumes/babs/working/boeings/")){
    hpc.mount <- "/Volumes/babs/working/boeings/"
} else if (dir.exists("Y:/working/boeings/")){
    hpc.mount <- "Y:/working/boeings/"
} else if (dir.exists("/camp/stp/babs/working/boeings/")){
    hpc.mount <- "/nemo/stp/babs/working/boeings/"
} else {
    hpc.mount <- ""
}


FN <- paste0(hpc.mount, "Projects/reference_data/pwd_folder/babs.txt")
    dbTable <- read.delim(
      FN,
      header = F,
      sep = "\t",
      stringsAsFactors = F
    )
db.pwd <- as.vector(dbTable[1,1])

if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol"
} else {
    queryGS <- Obio@parameterList$geneIDcolumn
}


tempVec <- biologicSeqTools2::retrieve.gene.category.from.db(
    cat_id = "ag_lab_categories__10",
    password = db.pwd,
    gene.symbol = queryGS,
    user = Obio@parameterList$db.user,
    host = Obio@parameterList$host
)

dfTemp <-  Obio@dataTableList$dfClusterResiduals
dfTemp <- dfTemp[dfTemp$gene %in% tempVec, ]

clusterNames <- unique( Obio@parameterList$clusterNameOrder)

for (i in 1:length(clusterNames)){
  dfTemp <- dfTemp[order(dfTemp[, clusterNames[i]], decreasing = T), ]

  if (topNselection > nrow(dfTemp)){
      topNselection <- nrow(dfTemp)
  }

  geneVec <- as.vector(sort(dfTemp[1:topNselection, "gene"]))

  LRgeneList[[clusterNames[i]]] <- geneVec
}

HMgeneSelections[["LR_TF_Markers"]] <- LRgeneList


## Add DGE markers ##



## Make general markers heatmpa ##
dfGeneralMarkers <- Obio@dataTableList$dfGeneralMarkers
dfGeneralMarkersPos <- dfGeneralMarkers[dfGeneralMarkers$avg_diff > 0,]


dfT <- unique(OsC@meta.data[,c("clusterName", "seurat_clusters")])
dfT[["DGEnames"]] <- paste0("C",dfT$seurat_clusters)

dfGeneralMarkersPos <- merge(
  dfGeneralMarkersPos,
  dfT,
  by.x = "cluster",
  by.y = "DGEnames"
)

dfTemp <- dfGeneralMarkersPos

DGEgeneList <- list()
topNselection <- 5


clusterNames <- unique( Obio@parameterList$clusterNameOrder)

for (i in 1:length(clusterNames)){
  dfTemp2 <- dfTemp[dfTemp$clusterName == clusterNames[i],]
  dfTemp2 <- dfTemp2[order(dfTemp2[, "avg_diff"], decreasing = T), ]

  if (topNselection > nrow(dfTemp2)){
      selVal <- nrow(dfTemp2)
  } else {
      selVal <- topNselection
  }

  geneVec <- as.vector(sort(dfTemp2[1:selVal, "gene"]))
  if (length(geneVec) > 0){
    DGEgeneList[[clusterNames[i]]] <- geneVec
  }
}


HMgeneSelections[["DGE_Markers"]] <- DGEgeneList

## DGE TF markers
## Make general markers heatmpa ##
dfGeneralMarkers <- Obio@dataTableList$dfGeneralMarkers
dfGeneralMarkersPos <- dfGeneralMarkers[dfGeneralMarkers$avg_diff > 0,]


dfT <- unique(OsC@meta.data[,c("clusterName", "seurat_clusters")])
dfT[["DGEnames"]] <- paste0("C",dfT$seurat_clusters)

dfGeneralMarkersPos <- merge(
  dfGeneralMarkersPos,
  dfT,
  by.x = "cluster",
  by.y = "DGEnames"
)

dfTemp <- dfGeneralMarkersPos

## Get transcription factor genes ##
if (dir.exists("/Volumes/babs/working/boeings/")){
    hpc.mount <- "/Volumes/babs/working/boeings/"
} else if (dir.exists("Y:/working/boeings/")){
    hpc.mount <- "Y:/working/boeings/"
} else if (dir.exists("/camp/stp/babs/working/boeings/")){
    hpc.mount <- "/nemo/stp/babs/working/boeings/"
} else {
    hpc.mount <- ""
}


FN <- paste0(hpc.mount, "Projects/reference_data/pwd_folder/babs.txt")
    dbTable <- read.delim(
      FN,
      header = F,
      sep = "\t",
      stringsAsFactors = F
    )
db.pwd <- as.vector(dbTable[1,1])

if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol"
} else {
    queryGS <- Obio@parameterList$geneIDcolumn
}


tempVec <- biologicSeqTools2::retrieve.gene.category.from.db(
    cat_id = "ag_lab_categories__10",
    password = db.pwd,
    gene.symbol = queryGS,
    user = Obio@parameterList$db.user,
    host = Obio@parameterList$host
)

dfTemp <- dfTemp[dfTemp$gene %in% tempVec, ]


DGEgeneList <- list()
topNselection <- 5


clusterNames <- unique( Obio@parameterList$clusterNameOrder)

for (i in 1:length(clusterNames)){
  dfTemp2 <- dfTemp[dfTemp$clusterName == clusterNames[i],]
  dfTemp2 <- dfTemp2[order(dfTemp2[, "avg_diff"], decreasing = T), ]

  if (topNselection > nrow(dfTemp2)){
      selVal <- nrow(dfTemp2)
  } else {
      selVal <- topNselection
  }

  geneVec <- as.vector(sort(dfTemp2[1:selVal, "gene"]))
  if (length(geneVec) > 0){
    DGEgeneList[[clusterNames[i]]] <- geneVec
  }
}

HMgeneSelections[["DGE_TF_Markers"]] <- DGEgeneList


## Load gene sets from cat reference file
catFN <-  Obio@parameterList$catRefFile

if (!is.null(catFN) && file.exists(catFN)){
  dfCat <- read.delim(
    catFN,
    sep = "\t",
    stringsAsFactors = F
  )
}

## Add each cat to ref list
for (i in 1:ncol(dfCat)){
  catName <- colnames(dfCat)[i]
  geneVec <- unique(
    as.vector(
      dfCat[3:nrow(dfCat), i]
    )
  )
  geneVec <- geneVec[geneVec %in% row.names(OsC)]
  catList <- list()
  catList[[catName]] <- geneVec
  HMgeneSelections[[catName]] <- catList
}


# ## Custom gene lists
# HMgeneSelections[["Custom_Top2_Markers"]]  <- list(
#     "GC1" = c("Galntl6", "Esrrg"),
#     "GC2" = c("Oxr1", "Adamts19"),
#     "GC3" = c("Hcn1", "Nrg3"),
#     "GC4" = c("Apoe", "Ptn"),
#     "GC5" = c("Dcc", "Mgat4c"),
#     "GC6" = c("Lrp1b", "Thsd7b"),
#     "GC7" = c("Macrod2", "Cntn5"),
#     "GC8" = c("Il1rapl2", "Kcnt2"),
#     "GC9" = c("Tmem132d", "Unc5d")
# )
#
# HMgeneSelections[["Heatmap_Channels"]]  <- list(
#     "VGSC" = c("Scn1a", "Scn2a", "Scn1a","Scn2a", "Scn3a", "Scn4a","Scn5a", "Scn8a", "Scn9a", "Scn10a", "Scn11a"),
#     "VGPC" = c("Kcna2", "Kcna3", "Kcna4", "Kcna5", "Kcnb1", "Kcnb2", "Kcnc1", "Kcnc2", "Kcnc3", "Kcnc4", "Kcnd1", "Kcnd2","Kcnd3", "Kcnq1", "Kcnq2", "Kcnq3", "Kcnq4", "Kcnq5"),
#     "CaGC" = c("Cacna1a", "Cacna1b", "Cacna1c", "Cacna1d", "Cacna1e", "Cacna1f"),
#     "ClC" = c(
#       "Clcn1",
#       "Clcn2",
#       "Clcn3",
#       "Clcn4",
#       "Clcn5",
#       "Clcn6",
#       "Clcn7",
#       "Gabra1",
#       "Gabra2",
#       "Gabra3",
#       "Gabra4",
#       "Gabra5",
#       "Gabra6",
#       "Gabrb1",
#       "Gabrb2",
#       "Gabrb3",
#       "Gabrb4",
#       "Gabrb5",
#       "Gabrg1"
#     ),
#     "VGSCbeta" = c("Scn1b", "Scn2b", "Scn3b", "Scn4b"),
#     "IRPC" = c("Kcnj1", "Kcnj2","Kcnj3", "Kcnj4", "Kcnj5", "Kcnj6", "Kcnj8", "Kcnj9", "Kcnj10", "Kcnj11", "Kcnj12", "Kcnj13", "Kcnj14","Kcnj15", "Kcnj16","Kcnj18", "Kcnj19"),
#     "HCNC" = c("Hcn1", "Hcn2", "Hcn3", "Hcn4"),
#     "NaKExc" = c("Slc9a1", "Slc9a2", "Slc9a3", "Slc9a4","Slc9a5", "Slc9a6", "Slc9a7", "Slc9a8"),
#     "CaSenKC" = c("Kcnma1", "Kcnma2","Kcnma3","Kcnma4", "Kcnmb1", "Kcnmb2", "Kcnmb3", "Kcnmb4"),
#     "TrpC" = c("Trpa1","Trpa3", "Trpc1", "Trpc2","Trpc3", "Trpc4", "Trpc5", "Trpc6", "Trpc7", "Trpm1", "Trpm2","Trpm3","Trpm4", "Trpm5","Trpm6", "Trpm7","Trpm8","Trpv1","Trpv2","Trpv3", "Trpv4","Trpv5", "Trpv6")
# )


## done
################################


## For Violinplots we want single gene lists
library(tidyr) 

geneList <- lapply(HMgeneSelections, function(x) unique(unlist(x)))
geneList <- lapply(geneList, function(x) x[x %in% row.names(OsC)])
selVec <- unlist(lapply(geneList, function(x) length(x) != 0))
geneList <- geneList[selVec]

## Create colvec ##
group1ColorCol = "clusterColor"
group1NameCol = "clusterName"
#group2ColorCol = segmentationColorCol, 
#group2NameCol = segmentationCol,
dfCol <- unique(dfMeta[,c(group1ColorCol, group1NameCol)])
colVec <- dfCol[,group1ColorCol]
names(colVec) <- dfCol[,group1NameCol]

# dfCol2 <- unique(dfMeta[,c(group2ColorCol, group2NameCol)])
# colVec2 <- dfCol2[,group2ColorCol]
# names(colVec2) <- dfCol2[,group2NameCol]
# # 


plotList <- list()

chnkVec <- as.vector(NULL, mode = "character")

 textSize <- 1

for (i in 1:length(geneList)){
  
tag <- paste0("Dot_", names(geneList)[i])  
# geneList[[i]] <- geneList[[i]][rowSums(OsC@assays$RNA[geneList[[i]],]) != 0]
  
  if (length(geneList[[i]]) > 0 & length(geneList[[i]]) <=  50){
   
    # if (length(geneList[[i]]) > 50){
    #   dotScale <- 0.01
    # } else if (length(geneList[[i]]) > 30){
    #    dotScale <- 0.02
    # } else if (length(geneList[[i]]) > 20){
    #    dotScale <- 0.04
    # } else if (length(geneList[[i]]) > 10){
    #    dotScale <- 0.1
    # } else {
    #   dotscale <- 0.4
    # }
    #  
    ##
    dpGenes <- unique(geneList[[i]])
        legendNote <- paste0("The following genes were found in this category and the single-cell dataset: ", paste0(dpGenes, collapse=", "))
        
        OsC_DP <- OsC
        OsC_DP@meta.data$clusterName <- factor(OsC_DP@meta.data$clusterName, levels = Obio@parameterList[["clusterNameOrder"]])
        
        
        
        dfCol <- unique(OsC@meta.data[,c("clusterName", "clusterColor")])
if(!is.null(Obio@parameterList$clusterNameOrder)){
    row.names(dfCol) <- dfCol$clusterName
    dfCol <- dfCol[Obio@parameterList$clusterNameOrder,]
}
        colVec <- as.vector(dfCol$clusterColor)
        names(colVec) <- dfCol$clusterName
      
        textSize <- 2
        if (length(colVec) > 5){
            textSize <-1
        } else if (length(colVec) > 20){
            textSize <- 0.75
        } else if (length(colVec) > 40){
            textSize <- 0.5
        }

        Seurat::Idents(OsC_DP) <- "clusterName"

        library(ggplot2)
        library(tidyr)
        library(Seurat)

        plotList[[tag]] <- biologicSeqTools2::DotPlotSB(
            object = OsC_DP,
            features = dpGenes,
            #cols = cols,
            group.by = NULL,
            split.by = NULL,
            dot.scale = 4,
            col.min = 0,
            col.max = 5,
            assay = "RNA"
        ) + ggplot2::ggtitle(gsub("_", " ", tag)
        ) + ggplot2::coord_fixed(
        #) + coord_flip(
        ) + ggplot2::theme_bw() + ggplot2::theme(
                axis.title.y  = ggplot2::element_blank(),
                axis.title.x  = ggplot2::element_blank()
        )  + ggplot2::theme(axis.text.x = ggplot2::element_text(size=rel(textSize), angle = 45, hjust=1, color = colVec))
        
    
  
  
  FNbase <- paste0(tag, VersionPdfExt)

  FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
  FNrel <- paste0("report_figures/", FNbase)
            
  pdf(FN)
    print(plotList[[tag]])
  dev.off()

  figLegend <- paste0(
    '**Figure ', 
    figureCount, 
    ':** ',
    'Dotplot split by cluster for gene set ',gsub("_", " ", tag),'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>.'
  )
            
  figureCount <- figureCount + 1

  NewChnk <- paste0(
    "#### ", tag,
    "\n```{r dot_",
    tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
    figLegend,"'}\n",
    "\n",
    "\n print(plotList[['",tag,"']])",
    "\n cat(  '\n')",
    "\n\n\n```\n"   
)

  chnkVec <- c(
    chnkVec,
    NewChnk
  )
  }
} # end for loop

# plotList <- addHeatmap2List(
#     OsC = OsC,
#     geneGroupList = geneGroupList,
#     relativeExpression = TRUE,
#     plotList = plotList,
#     cmdVec = NULL,
#     tag = "Channels_Rel",
#     showAllLegends = TRUE
#     )


#pdf("../../../../html_local/report_figures/custom.dotplots.plots.asl545.V2.pdf")
#plotList
#dev.off()

if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}    
    
```


### Dotplots {`r tabVar`}

In this section heatmaps and dotplots for various gene categories are provided.

:::: {.panel-tabset .nav-pills}
```{r Cluster_dotplot_overview, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```
::::

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

if (exists("whiteListWorkspace")){
    rm(list = setdiff(ls(), whiteListWorkspace))
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```