---
format:
    html:
        embed-rmd: true
        output-ext: "htm"
---

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

```



```{r, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE}
###############################################################################
##  Load packages                                                            ##

version <- "dev"
a <- unlist(strsplit(getwd(), "/"))
folderNameTag <- a[length(a)]

VersionPdfExt <- paste0(folderNameTag,".",version,".V", gsub("-", "", Sys.Date()), ".pdf")

rasterDpi <- 300
calculateDGE <- TRUE
nCellMax <- 5000

if (!exists("figureCount"){
    figureCount <- 1
}
```

```{r child = '01-set.parameters.Rmd', eval=TRUE}
```




```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```
