---
format:
    html:
        embed-rmd: true
        output-ext: "htm"
---
## Enrichment Analysis

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

```

```{r create-pca-enrichment-data, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE, error=F}
Obio@dbDetailList$db.user <- "babs"
## Create enriched genes list ##
EnrichedGenesList <- list()
if (exists("dfDGEstore")){
    dfAllPlots <- dfDGEstore
} else {
    dfAllPlots <- Obio@dataTableList[["DGE_table"]]
}

## Set species
if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
  queryGS <- "hgnc_symbol"
} else {
  queryGS <- Obio@parameterList$geneIDcolumn
}

###############################################################################
## Create lists with up and downregulated genes                              ##
for (i in 1:length(DGEtagVec)){


  tag <- paste0("MA_Plot_", DGEtagVec[i])
  tagGLpos <- paste0(DGEtagVec[i], "_pos")
  tagGLneg <- paste0(DGEtagVec[i], "_neg")

  selVec <- c(
    "gene",
    names(dfAllPlots)[grep(paste0(DGEtagVec[i], "$"), names(dfAllPlots))]
  )

  dfPlot <- dfAllPlots[,selVec]
  pos <- grep("included", names(dfPlot))
  if (length(pos) == 0){
    dfPlot[["included"]] <- "+"
  }

  logFCtwoSD <- 2*sd(dfPlot[,grep("_logFC_", names(dfPlot))])

  dfPlot[["DGE_Status"]] <- "Unchanged"
  dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] > logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Up"
  EnrichedGenesList[[tagGLpos]] <- unique(dfPlot[dfPlot$DGE_Status == "Up", "gene"])

  dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] < -1 *logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Down"
  EnrichedGenesList[[tagGLneg]] <- unique(dfPlot[dfPlot$DGE_Status == "Down", "gene"])
}
## Done create lists with up and downregulated genes                         ##
###############################################################################

#library(knitr::)
#library(ggplot2)

#save.image("temp.RData")
#library(clusterProfiler)

###############################################################################
## Create gmt list                                                           ##
gmtList <- list()
pos <- grep("clusterSigEnrichmentList", slotNames(Obio))

if (length(pos) > 0){
  if (is.null(Obio@clusterSigEnrichmentList)){
    dbtableList <- list(
      "Cell Type Signatures" = "mysigdb_sc_sig",
      "Cell Type Signatures" = "cibersort_L22",
      "GO-MF" = "mysigdb_c5_MF",
      "Pathways" = "mysigdb_c2_1329_canonical_pathways",
      "Protein Complexes" = "networkcategories"
    )
  } else {
    dbtableList <- Obio@clusterSigEnrichmentList
  }
} else {
  dbtableList <- list(
    "Cell Type Signatures" = "mysigdb_sc_sig",
    "Cell Type Signatures" = "cibersort_L22",
    "GO-MF" = "mysigdb_c5_MF",
    "Pathways" = "mysigdb_c2_1329_canonical_pathways",
    "Protein Complexes" = "networkcategories"
  )
}


rmVec <- grep("Cell Type Signatures", names(dbtableList))
if (length(rmVec) > 0){
  dbtableList <- dbtableList[-rmVec]
}

###############################################################################
## Download gene categoies                                                   ##
## start table loop
for (m in 1:length(dbtableList)){
  dfTemp <- unique(
    import.db.table.from.db(
      host = Obio@dbDetailList$host,
      dbname = Obio@dbDetailList$ref.cat.db,
      dbtable = dbtableList [[m]],
      password = db.pwd,
      user = Obio@dbDetailList$db.user
    )
  )

  ## Remove duplicated entries ##
  dfTemp <- dfTemp[!(duplicated(dfTemp$cat_name)),]

  rmVec <- grep("temp_", dfTemp$cat_type)
  if (length(rmVec) > 0){
    dfTemp <- dfTemp[-rmVec, ]
  }

  dfTemp <- unique(
    dbcat2gmt(
      dfTemp, # As downloaded from reference_categories_db_new database
      gene.id.column = queryGS
    )
  )

  dfTemp <- unique(dfTemp[!duplicated(as.vector(dfTemp[,1])), ])

  write.table(
    dfTemp,
    "temp.gmt.txt",
    row.names = F,
    sep = "\t",
    col.names = F,
    quote = F
  )

  CPgmt <- clusterProfiler::read.gmt("temp.gmt.txt")
  unlink("temp.gmt.txt")
  CPgmt <- unique(CPgmt[CPgmt$gene != "", ])

  gmtList[[dbtableList[[m]]]] <- CPgmt
} #End table m loop

## Edit collection names for plot
names(gmtList) <- gsub("mysigdb_", "",names(gmtList))
names(gmtList) <- gsub("c2_1329_canonical_p", "P",names(gmtList))
names(gmtList) <- gsub("sc_sig", "CellSig",names(gmtList))
names(gmtList) <- gsub("cibersort_L22", "CellSig",names(gmtList))
names(gmtList) <- gsub("c5_", "GO_",names(gmtList))
names(gmtList) <- gsub("networkcategories", "Complexes",names(gmtList))

## Done making gmt list                                                      ##
###############################################################################

## Select colors ##
#library(scales)
enrCols <- scales::hue_pal()(length(gmtList))
names(enrCols) <- substr(names(gmtList),1,10)


###############################################################################
## Generate plot list                                                        ##

# Initiate plotlist to collect results
plotList <- list()
chnkVec <- as.vector(NULL, mode = "character")

# Initiate Excel workbook to collect results
wb <- openxlsx::createWorkbook()

for (j in 1:length(DGEtagVec)){
  posTestGeneSet <- as.vector(
    unique(
      EnrichedGenesList[[paste0(DGEtagVec[j], "_pos")]]
    )
  )


  negTestGeneSet <- as.vector(
    unique(
      EnrichedGenesList[[paste0(DGEtagVec[j], "_neg")]]
    )
  )

  if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol"
  } else {
    queryGS <- Obio@parameterList$geneIDcolumn
  }

  if (Obio@parameterList$host == "10.27.241.234"){
    urlString <- "biologic.thecrick.org"
  } else {
    urlString <- "biologic.crick.ac.uk"
  }

  colVec <- c("#009900", "#000080")
  pvalueCutoff <- 0.5
  topMaxCat <- 10

  ## Get background gene set ##
  #backgroundGeneVec <- row.names(OsC[["RNA"]]@counts)
  if ((length(posTestGeneSet) >= 3) | (length(negTestGeneSet) >= 3)){
    ## Do enrichment ##
    first <- TRUE
    if (length(posTestGeneSet) >= 3){
      for (k in 1:length(gmtList)){
        egmt <- data.frame(
          clusterProfiler::enricher(
            negTestGeneSet,
            TERM2GENE=gmtList[[k]],
            pvalueCutoff = pvalueCutoff
          )
        )
        if (!is.null(egmt)){
          if (nrow(egmt) > 0){
            egmt[["Collection"]] <- substr(names(gmtList)[k], 1,10)
          }
          if (first){
            dfTempEnriched <- egmt
            first <- FALSE
          } else {
            dfTempEnriched <- rbind(
              dfTempEnriched,
              egmt
            )
          }

        }
      }

      if (exists("dfTempEnriched") && nrow(dfTempEnriched) > 0){
        dfTempEnriched[["direction"]] <- "positive"
        dfTempEnriched[["log10FDR"]] <- log10(dfTempEnriched$p.adjust)
        dfTempEnriched <- dfTempEnriched[order(dfTempEnriched$log10FDR, decreasing = F),]
        dfTempEnriched <- na.omit(dfTempEnriched)
        dfEnriched <- dfTempEnriched

        if (nrow(dfTempEnriched) > topMaxCat){
          dfTempEnriched <- dfTempEnriched[1:topMaxCat, ]
        }
      }


    } # end positive

    ## Now the negative side ##
    if (length(negTestGeneSet) >= 3){
      first <- TRUE
        for (k in 1:length(gmtList)){
          egmt <- data.frame(
          clusterProfiler::enricher(
            posTestGeneSet,
            TERM2GENE=gmtList[[k]],
            pvalueCutoff = pvalueCutoff
          )
        )
        if (!is.null(egmt)){
          if (nrow(egmt) > 0){
            egmt[["Collection"]] <- substr(names(gmtList)[k], 1,10)
          }
          if (first){
            dfTempEnrichedNeg <- egmt
            first <- FALSE
          } else {
            dfTempEnrichedNeg <- rbind(
              dfTempEnrichedNeg,
              egmt
            )
          }

        }
      }

      if (exists("dfTempEnrichedNeg") && nrow(dfTempEnrichedNeg) > 0){
        dfTempEnrichedNeg[["direction"]] <- "negative"
        dfTempEnrichedNeg[["log10FDR"]] <- -1*log10(dfTempEnrichedNeg$p.adjust)
        dfTempEnrichedNeg <- dfTempEnrichedNeg[order(dfTempEnrichedNeg$log10FDR, decreasing = T),]
        dfTempEnrichedNeg <- na.omit(dfTempEnrichedNeg)
        dfEnrichedNeg <- dfTempEnrichedNeg

        if (nrow(dfTempEnrichedNeg) > topMaxCat){
          dfTempEnrichedNeg <- dfTempEnrichedNeg[1:topMaxCat, ]
        }
      }
    } # end negative



    ## Make plot
    if ((nrow(dfTempEnriched) > 0) | (nrow(dfTempEnrichedNeg) > 0)){
      dfSel <- rbind(
        dfTempEnriched,
        dfTempEnrichedNeg
      )

      dfSel <- na.omit(dfSel)
      dfSel <- dfSel[order(dfSel$log10FDR),]
      dfSel$log10FDR <- round(dfSel$log10FDR, 2)

      dfSel[["Category"]] <- ""
      dfSel[dfSel$log10FDR >= 0, "Category"] <- "Enr."
      dfSel[dfSel$log10FDR < 0, "Category"] <- "Depl."

      for (l in 1:nrow(dfSel)){
        if (nchar(dfSel[l, "ID"]) > 30){
          part1 <- substr(dfSel[l, "ID"], 1, 30)
          part2 <- substr(dfSel[l, "ID"], 31, 60)
          dfSel[l, "ID"] <- paste0(part1, " \n ", part2)

        }
      }


      #dfSel$Term <- gsub("\\(GO", "\\\n\\(GO", dfSel$Term)

      dfSel$ID <- factor(dfSel$ID, levels = unique(dfSel$ID))

      plotList[[paste0("PCA_ENR_", j)]] <- ggplot2::ggplot(
        data=dfSel, ggplot2::aes(x= ID, y=log10FDR, fill=Collection, order=log10FDR)
      ) + ggplot2::geom_bar(stat="identity", colour="black"
      ) + ggplot2::coord_flip() + ggplot2::scale_fill_manual(values=enrCols
      ) + ggplot2::theme_bw(
      ) +  ggplot2::theme(
        axis.text.y   = ggplot2::element_text(size=8),
        axis.text.x   = ggplot2::element_text(size=8),
        axis.title.y  = ggplot2::element_text(size=8),
        axis.title.x  = ggplot2::element_text(size=8),
        axis.line = ggplot2::element_line(colour = "black"),
        panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
        plot.title = ggplot2::element_text(hjust = 0.5, size = 12)
      ) + ggplot2::labs(title = paste0("Comparison ", DGEtagVec[j]," enriched genes") ,y = "-log10(FDR)", x = ""
      ) + ggplot2::geom_hline(yintercept = c(-log10(0.05), log10(0.05)), color = "grey", size=0.5, lty=2
      ) + ggplot2::geom_hline(yintercept = 0, color = "black", size=0.5
      )
      cat("  \n")



      ## Save to file ##
      FNbase <- paste0("DGE_comparison_", DGEtagVec[j],".enriched.genes", VersionPdfExt)
      FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
      FNrel <- paste0("report_figures/", FNbase)


      pdf(FN)
      print(plotList[[paste0("PCA_ENR_", j)]])
      dev.off()

      link <- paste0(
        '<a href="https://', urlString, '/',
        Obio@parameterList$project_id,
        '/category-view?category_type=GO-BP" target="_blank">CategoryView</a>'
      )

      ## Create table link for category enrichment table
      ## Set file paths ##
      baseFN <- paste0(
        Obio@parameterList$project_id,
        ".DGE.cat.enrichment.table.", folderNameTag, ".",version,".xlsx"
      )

      FNrel <- paste0("report_tables/", baseFN)

      outPutFN <- paste0(
        reportTableDir,
        baseFN
      )

      tableLink2 <- paste0(
        'https://',
        urlString,
        '/mdata/',project_id, '/html/',
        FNrel
      )
      ## done


      ## Create R markdown chunk ##
      figLegend <- paste0(
        '**Figure ',
        figureCount,
        '**: Category enrichment analysis for the top genes that have  <font color = "',colVec[2],'"> the most positive </font> and <font color = "',colVec[1],'">the most negative</font> log-fold change values in dimension ',
        DGEtagVec[j],
        ' associated with them. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>. To view these gene sets in the context of your data, go to ',link,' and find these categories using the search box. ',
        'Download a table with enrichment results <a href="',tableLink2,'"target="_blank">here</a>.'
      )






      figureCount <- figureCount + 1

      NewChnk <- paste0(
        "#### ", DGEtagVec[j],
        "\n```{r enrichr_",
        j,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
        figLegend,"'}\n",
        "\n",
        "\n print(plotList[['",paste0("PCA_ENR_", j),"']])",
        "\n cat(  '\n')",
        "\n\n\n```\n"
      )

      chnkVec <- c(
        chnkVec,
        NewChnk
      )


      ####################################################################
      ## Create full output table for this iteration                    ##
      dfResTemp <- rbind(
        dfEnriched,
        dfEnrichedNeg
      )

      dfResTemp[["comparison"]] <- tag

      ## Make one excel sheet per DGE comparison
      sheetName <- paste0(substr(DGEtagVec[j],1,23), "_comp_",j)

      openxlsx::addWorksheet(wb, sheetName)
      hs1 <- openxlsx::createStyle(
        fontColour = "#ffffff",
        fgFill = "#000000",
        halign = "CENTER",
        textDecoration = "Bold"
      )

      openxlsx::writeData(wb, sheetName, dfResTemp, startRow = 1, startCol = 1, headerStyle = hs1)
      openxlsx::freezePane(wb, sheetName ,  firstActiveRow = 2)
      openxlsx::addFilter(wb, sheetName, row=1, cols = 1:ncol(dfResTemp))

      ## Create one big table with all dge results
      # if (j==1){
      #   dfResTable <- dfResTemp
      # } else {
      #   dfResTable <- rbind(
      #     dfResTable,
      #     dfResTemp
      #   )
      # }
      ## Done                                                           ##
      ####################################################################
    } #end make plot if


  } ## Done with per dimension loops plot list if


}

###############################################################################
## Create cat enrichment table                                               ##

## Add ref-gene column ##
#dfTemp[["ref_gene"]] <- ""
#dfTemp[dfTemp$gene %in% refGenes, "ref_gene"] <- "+"

library(openxlsx)

## Enrichment result table is called dfResTable

if (!dir.exists( paste0(
   Obio@parameterList$html_local,
   "report_tables/"))){
  dir.create(paste0(
   Obio@parameterList$html_local,
   "report_tables/"))
}

baseFN <- paste0(
   Obio@parameterList$project_id,
   ".DGE.cat.enrichment.table.",folderNameTag, ".",version,".xlsx"
)


outPutFN <- paste0(
     Obio@parameterList$html_local,
      "report_tables/",
     baseFN
)


FNrel <- paste0("report_table/", baseFN)


## Filter is inactivated, as it does not appear to be compatible with the current version of Excel
#addFilter(wb, 1, row = 1, cols = 1:ncol(dfOutput))

## Style headers ##


saveWorkbook(
  wb,
  outPutFN ,
  overwrite = TRUE
)

## Done creating Excel output files                                          ##
###############################################################################



if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}
```

### Category Enrichments Differential Gene Expression Results {`r tabVar`}
:::: {.panel-tabset .nav-pills}
```{r create-cat-enrichment-plot, echo=T, eval=TRUE, warning=FALSE, results='asis'}
###############################################################################
## Do category enrichment on clusters                                        ##
cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))
## Done doing enrichment on clusters                                         ##
###############################################################################


```
::::

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```
