---
format:
    html:
        embed-rmd: true
        output-ext: "htm"
---

## MA- and Violin Plots

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

```

```{r, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE}

###############################################################################
## Make scDGE MA-plots                                                       ##
topNgenes <- 20
plotList <- list()
chnkVec <- as.vector(NULL, mode = "character")


if (exists("dfDGEstore")){
    dfAllPlots <- dfDGEstore
} else {
    dfAllPlots <- Obio@dataTableList[["DGE_table"]]
}

for (i in 1:length(DGEtagVec)){
    tag <- paste0("MA_Plot_", DGEtagVec[i])
    label <- gsub("_", " ", DGEtagVec[i])

    selVec <- c(
        "gene",
        names(dfAllPlots)[grep(paste0(DGEtagVec[i], "$"), names(dfAllPlots))]
    )

    dfPlot <- dfAllPlots[,selVec]
    pos <- grep("included", names(dfPlot))
    if (length(pos) == 0){
        dfPlot[["included"]] <- "+"
    }

    logFCtwoSD <- 2*sd(dfPlot[,grep("_logFC_", names(dfPlot))])

    dfPlot[["DGE_Status"]] <- "Unchanged"
    dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] > logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Up"
    dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] < -1 *logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Down"

    colVec <- c("red", "blue", "black")
    names(colVec) <- c("Up", "Down", "Unchanged")


    dfPlot[["X"]] <- dfPlot[,grep("add_MA_cts_MA_Avg", names(dfPlot))]
    dfPlot[["Y"]] <- dfPlot[,grep("_logFC", names(dfPlot))]
    dfPlot[["intensity_weighted_lg10p"]] <- dfPlot[["X"]] * dfPlot[["Y"]]

    dotsize  = 1.25
    if (nrow(dfPlot) > 10000){
      dotsize  = 1
    } else if (nrow(dfPlot) > 20000){
      dotsize = 0.75
    } else if (nrow(dfPlot) > 50000){
      dotsize = 0.5
    }

    logFClims <- ceiling(max(abs(dfPlot$Y)))

    ## Add to-regulated gene names ##
    topNgenes <- 20
    dfPlot <- dfPlot[order(dfPlot$intensity_weighted_lg10p, decreasing = T), ]
    topGenes <- as.vector(dfPlot[1:topNgenes,"gene"])

    dfPlot <- dfPlot[order(dfPlot$intensity_weighted_lg10p, decreasing = F), ]

    bottomGenes <- as.vector(dfPlot[1:topNgenes,"gene"])

    dfPlot[["label"]] <- ""
    dfPlot[dfPlot[,"gene"] %in% c(topGenes, bottomGenes), "label"] <- dfPlot[dfPlot[,"gene"] %in% c(topGenes, bottomGenes), "gene"]



    plotList[[tag]] <- ggplot2::ggplot(data=dfPlot[dfPlot$included == "+",],
        ggplot2::aes(X, Y, color=DGE_Status, label = label)) +
        ggplot2::geom_hline(yintercept = c(logFCtwoSD, -1 * logFCtwoSD), col = "darkgrey", lty=2) +
        ggrastr::rasterize(ggplot2::geom_point( shape=16, size = as.numeric(dotsize),alpha = 0.7), dpi = rasterDpi) +
        ggplot2::xlab(paste0("log10 Avg Intensity ", gsub("_", " ",label))) +
        ggplot2::ylab(paste0("log2-Fold Change ", gsub("_", " ",label))) +
        ggplot2::theme_bw()  +
        ggplot2::theme(
            axis.text.y   = ggplot2::element_text(size=8),
            axis.text.x   = ggplot2::element_text(size=8),
            axis.title.y  = ggplot2::element_text(size=8),
            axis.title.x  = ggplot2::element_text(size=8),
            axis.line = ggplot2::element_line(colour = "black"),
            panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
            plot.title = ggplot2::element_text(hjust = 0.5, size = 12)) +
        ggplot2::guides(col = ggplot2::guide_legend(override.aes = list(shape = 16, size = legendDotSize))) +
        ggplot2::ggtitle(paste0("MA-stype Plot for DGE Comparison ", gsub("_", " ", label))) +
      ggplot2::ylim(logFClims, -1 * logFClims) +
      ggplot2::scale_color_manual("DGE Status" ,values = colVec) +
      ggplot2::scale_y_continuous(breaks=c(seq(-20,20,2)))


      ## Add labels
      plotList[[tag]] <- plotList[[tag]] + ggrepel::geom_text_repel(size = 3, max.iter = 10000)



      FNbase <- paste0(tag, ".wo.label.",VersionPdfExt)
      FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
      FNrel <- paste0("report_figures/", FNbase)

      pdf(FN)
          print(plotList[[tag]])
      dev.off()

      ## downsize for report plot
      # plotList[[tag]] <- ggrastr::rasterize(
      #   plotList[[tag]],
      #   layers='Point',
      #   dpi = 400
      # )

      xLabel <- names(dfPlot[grep("MA_Avg", names(dfPlot))])
      yLabel <- names(dfPlot[grep("_logFC_", names(dfPlot))])
      link <- paste0('<a href="https://',urlString,'/',Obio@parameterList$project_id,'/scatterplot?x_axis=',xLabel,'&y_axis=',yLabel,'" target="_blank">here</a>')

      figLegend <- paste0(
      '**Figure ',
      figureCount,
                ':** ',
                ' MA-style plot for differential gene expression comparison ',gsub("_", " ", DGEtagVec[i]),'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>. ',
                'An interactive version of this figure can be found ', link, '. ',
                tableString
            )

      figureCount <- figureCount + 1

      NewChnk <- paste0(
          "#### ", tag,
          "\n```{r MA_DGE_",
          tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
          figLegend,"'}\n",
          "\n",
          "\n print(plotList[['",tag,"']])",
          "\n cat(  '\n')",
          "\n\n\n```\n"
      )

      chnkVec <- c(
          chnkVec,
          NewChnk
      )

      ## Done creating DGE selection plot                                      ##
      ###########################################################################




}


## Done MA- plots                                                            ##
###############################################################################

if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}
```

### DGE MA-style Plots {`r tabVar`}
:::: {.panel-tabset .nav-pills}
```{r DGE_MA_plot, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```
::::

```{r data_Volcano_plots, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE}
###############################################################################
## Make Volcano plots
plotList <- list()
chnkVec <- as.vector(NULL, mode = "character")

if (exists("dfDGEstore")){
    dfAllPlots <- dfDGEstore
} else {
    dfAllPlots <- Obio@dataTableList[["DGE_table"]]
}

for (i in 1:length(DGEtagVec)){
    tag <- paste0("Volcano_Plot_", DGEtagVec[i])
    label <- gsub("_", " ", DGEtagVec[i])

    selVec <- c(
        "gene",
        names(dfAllPlots)[grep(paste0(DGEtagVec[i], "$"), names(dfAllPlots))]
    )

    dfPlot <- dfAllPlots[,selVec]
    pos <- grep("included", names(dfPlot))
    if (length(pos) == 0){
        dfPlot[["included"]] <- "+"
    }

    logFCtwoSD <- 2*sd(dfPlot[,grep("_logFC_", names(dfPlot))])

    dfPlot[["DGE_Status"]] <- "Unchanged"
    dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] > logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Up"
    dfPlot[dfPlot[,grep("_logFC_", names(dfPlot))] < -1 *logFCtwoSD & dfPlot[,grep("_padj_", names(dfPlot))] < 0.05, "DGE_Status"] <- "Down"

    colVec <- c("red", "blue", "black")
    names(colVec) <- c("Up", "Down", "Unchanged")


    dfPlot[["X"]] <- dfPlot[,grep("_logFC", names(dfPlot))]
    dfPlot[["Y"]] <- dfPlot[,grep("_lg10p_", names(dfPlot))]
    dfPlot[["XY_weighted"]] <- dfPlot[["X"]] * dfPlot[["Y"]]

    dotsize  = 1.25
    if (nrow(dfPlot) > 10000){
      dotsize  = 1
    } else if (nrow(dfPlot) > 20000){
      dotsize = 0.75
    } else if (nrow(dfPlot) > 50000){
      dotsize = 0.5
    }

    logFClims <- ceiling(max(abs(dfPlot$X)))

    ## Add to-regulated gene names ##
    topNgenes <- 20
    dfPlot <- dfPlot[order(dfPlot$XY_weighted, decreasing = T), ]
    topGenes <- as.vector(dfPlot[1:topNgenes,"gene"])

    dfPlot <- dfPlot[order(dfPlot$XY_weighted, decreasing = F), ]
    bottomGenes <- as.vector(dfPlot[1:topNgenes,"gene"])

    dfPlot[["label"]] <- ""
    dfPlot[dfPlot[,"gene"] %in% c(topGenes, bottomGenes), "label"] <- dfPlot[dfPlot[,"gene"] %in% c(topGenes, bottomGenes), "gene"]


    plotList[[tag]] <- ggplot2::ggplot(
        data=dfPlot[dfPlot$included == "+",],
        ggplot2::aes(X, Y, color=DGE_Status, label = label)) +
        ggplot2::geom_vline(xintercept = c(logFCtwoSD, -1 * logFCtwoSD), col = "darkgrey", lty=2) +
        ggplot2::geom_vline(xintercept = 0, col = "darkgrey") +
        ggplot2::geom_hline(yintercept = 0, col = "darkgrey") +
        ggrastr::rasterize(ggplot2::geom_point( shape=16, size = as.numeric(dotsize),alpha = 0.7), dpi = rasterDpi) +
        ggplot2::xlab(paste0("log2-Fold Change ", gsub("_", " ",label))) +
        ggplot2::ylab(paste0("-log10(adj p-value) ", gsub("_", " ",label))) +
        ggplot2::theme_bw()  +  ggplot2::theme(
          axis.text.y   = ggplot2::element_text(size=8),
          axis.text.x   = ggplot2::element_text(size=8),
          axis.title.y  = ggplot2::element_text(size=8),
          axis.title.x  = ggplot2::element_text(size=8),
          axis.line = ggplot2::element_line(colour = "black"),
          panel.border = ggplot2::element_rect(colour = "black", fill=NA, size=1),
          plot.title = ggplot2::element_text(hjust = 0.5, size = 12)) +
      ggplot2::guides(col = ggplot2::guide_legend(override.aes = list(shape = 16, size = legendDotSize))) +
      ggplot2::ggtitle(paste0("Volcano Plot for DGE Comparison ", gsub("_", " ", label))) +
      ggplot2::ylim(logFClims, -1 * logFClims) +
      ggplot2::scale_color_manual("DGE Status" ,values = colVec) +
      ggplot2::scale_y_continuous(breaks=c(seq(0,400,50))) +
      ggplot2::scale_x_continuous(breaks=c(seq(-400,400,2)))


      ## Add labels
      # Make plots without labels
      plotList[[tag]] <- plotList[[tag]] + ggrepel::geom_text_repel(size = 3, max.iter = 10000)


      FNbase <- paste0(tag, ".wo.label.",VersionPdfExt)
      FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
      FNrel <- paste0("report_figures/", FNbase)

      pdf(FN)
          print(plotList[[tag]])
      dev.off()

      ## downsize for report plot
      # plotList[[tag]] <- ggrastr::rasterize(
      #   plotList[[tag]],
      #   layers='Point',
      #   dpi = 700
      # )

      xLabel <- names(dfPlot[grep("_logFC_", names(dfPlot))])
      yLabel <- names(dfPlot[grep("_lg10p_", names(dfPlot))])
      link <- paste0('<a href="https://',urlString,'/',Obio@parameterList$project_id,'/scatterplot?x_axis=',xLabel,'&y_axis=',yLabel,'" target="_blank">here</a>')



      figLegend <- paste0(
      '**Figure ',
      figureCount,
                ':** ',
                ' Volcano plot for differential gene expression comparison ',gsub("_", " ", DGEtagVec[i]),'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>. ',
                'An interactive version of this figure can be found ', link, '. ',
                tableString
            )

      figureCount <- figureCount + 1

      NewChnk <- paste0(
          "#### ", tag,
          "\n```{r Volcano_DGE_",
          tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
          figLegend,"'}\n",
          "\n",
          "\n print(plotList[['",tag,"']])",
          "\n cat(  '\n')",
          "\n\n\n```\n"
      )

      chnkVec <- c(
          chnkVec,
          NewChnk
      )

      ## Done creating DGE selection plot                                      ##
      ###########################################################################




}



## Done Volcano plots
###############################################################################

if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}
```

### DGE Volcano Plots {`r tabVar`}
:::: {.panel-tabset .nav-pills}
```{r DGE_volcano_plot, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```
::::

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```
