---
format:
  html:
    embed-rmd: true
    output-ext: "htm"
---

## Create Heatmaps

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}

FN <- "../../../../workdir/temp/temp.workspace.RData"
if (file.exists(FN)){
  load(FN)
} else {
  exit("No workspace found. Please run the previous step first and make sure it finished successfully.")
}

```

```{r process_heatmap_data, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE, error=F}

## Get transcription factor genes ##
if (dir.exists("/Volumes/babs/working/boeings/")){
    hpc.mount <- "/Volumes/babs/working/boeings/"
} else if (dir.exists("Y:/working/boeings/")){
    hpc.mount <- "Y:/working/boeings/"
} else if (dir.exists("/camp/stp/babs/working/boeings/")){
    hpc.mount <- "/nemo/stp/babs/working/boeings/"
} else {
    hpc.mount <- ""
}


FN <- paste0(hpc.mount, "Projects/reference_data/pwd_folder/babs.txt")
    dbTable <- read.delim(
      FN,
      header = F,
      sep = "\t",
      stringsAsFactors = F
    )
db.pwd <- as.vector(dbTable[1,1])

if (Obio@parameterList$geneIDcolumn != "mgi_symbol" & Obio@parameterList$geneIDcolumn != "hgnc_symbol") {
    queryGS <- "hgnc_symbol"
} else {
    queryGS <- Obio@parameterList$geneIDcolumn
}


TFs <- biologicSeqTools2::retrieve.gene.category.from.db(
    cat_id = "ag_lab_categories__10",
    password = db.pwd,
    gene.symbol = queryGS,
    user = Obio@parameterList$db.user,
    host = Obio@parameterList$host
)

GO_Secretion <-  biologicSeqTools2::retrieve.gene.category.from.db(
                          cat_id = "mysigdb_c5_BP__1347",
                          password = db.pwd,
                          gene.symbol = queryGS,
                          user = Obio@dbDetailList$db.user,
                          host = Obio@dbDetailList$host
                    )


## Interesting genes for each cluster are stored in this list:
# EnrichedGenesList

## Create a heatmap list for each element of the above list

############################################################
## Merge _up and _down arms for the heatmap


#hmVec <- names(EnrichedGenesList)
if (!exists("HMgeneSelections")){
  HMgeneSelections <- list()
}


for (i in 1: length(DGEtagVec)){
  tag <- paste0("HM_", DGEtagVec[i])

  selNames <- names(EnrichedGenesList)[grep(DGEtagVec[i] ,names(EnrichedGenesList))]
  selPos <- grep(DGEtagVec[i] ,names(EnrichedGenesList))

  geneVec <- sort(unique(Reduce(c,EnrichedGenesList[selNames])))

  TFgeneVec <- geneVec[geneVec %in% TFs]
  secGeneVec <- geneVec[geneVec %in% GO_Secretion]
  RestGeneVec <- geneVec[!(geneVec %in% unique(c(TFgeneVec, secGeneVec)))]

  catList <- list()

  if (length(TFgeneVec) > 0){
    catList[["TFs"]] <- TFgeneVec
  }

  if (length(secGeneVec) > 0){
    catList[["Secretion"]] <- secGeneVec
  }

  if (length( RestGeneVec) > 0){
     catList[["Other"]] <- RestGeneVec
  }


  HMgeneSelections[[tag]] <- catList


}

## Done creation of gene categories
##########################################

############################################
## Now making heatmaps

###############################################################################
## Depending on the project, another parameter can be used for heatmap       ##
## segmentation. The default is cluster_sampleName

segmentationCol <- "sampleName"

## Add column for averaging of cells
selClust <- paste0("clusterName_", segmentationCol)
OsC_HM <- OsC
OsC_HM@meta.data[[selClust]] <- paste0(
  OsC_HM@meta.data$clusterName,
  "-",
  gsub("_", "-", OsC_HM@meta.data[,segmentationCol])
)



###############################################################################
## Calculataing average across segmentation                                  ##
Seurat::Idents(OsC_HM) <- selClust
OsCsel <- Seurat::AggregateExpression(
  OsC_HM,
  return.seurat = TRUE
)


if (segmentationCol == "sampleName" & length(grep("^sampleColor$", names(OsC_HM@meta.data)) == 1)){
  segmentationColorCol <- "sampleColor"
} else{
  segmentationColorCol <- paste0(
    segmentationCol,
    "Color"
  )

  ## Colors can also be set manually here
  allCols <- unique(OsC_HM@meta.data[,segmentationCol])
  colorSel <- scales::hue_pal()(length(allCols))

  OsC_HM@meta.data[[segmentationColorCol]] <- OsC_HM@meta.data[[segmentationCol]]
  for (i in 1:length(allCols)){
    OsC_HM@meta.data[[segmentationColorCol]] <- gsub(
      allCols[i],
      colorSel[i],
      OsC_HM@meta.data[[segmentationColorCol]]

    )
  }

} # done with else of if clause



selVec <- c(
  "clusterName",
  "clusterColor",
  segmentationCol,
  segmentationColorCol,
  selClust
)


## Add color vector for segmentationCol ##

#dfAdd[["treatmentGroupColor"]] <- dfAdd$meta_Treatment
#dfAdd$treatmentGroupColor <- gsub("Control", "#3B5EF7", dfAdd$treatmentGroupColor)
#dfAdd$treatmentGroupColor <- gsub("MatB52", "#4DA868", dfAdd$treatmentGroupColor)
#dfAdd$treatmentGroupColor <- gsub("Regeneron", "#EE6C58", dfAdd$treatmentGroupColor)


dfAdd <- unique(OsC_HM@meta.data[,selVec])

if (packageVersion("Seurat") > "4.8.0"){
  row.names(dfAdd) <- gsub("_", "-", dfAdd[,selClust])
} else {
  row.names(dfAdd) <- dfAdd[,selClust]
}

OsCsel <- biologicToolsSC::addDf2seuratMetaData(
  obj = OsCsel,
  dfAdd = dfAdd
)

## Order of factors
segmentationColOrder <- sort(unique(OsCsel@meta.data[[segmentationCol]]))

if (segmentationCol == "sampleName" & !is.null(Obio@parameterList$sampleNameOrder)){
  segmentationColOrder <- Obio@parameterList$sampleNameOrder
}

OsCsel@meta.data[[segmentationCol]] <- factor(
  OsCsel@meta.data[[segmentationCol]],
  levels = segmentationColOrder
)

## Check if all clusters are present in clustername order
check <- unique(OsCsel@meta.data$clusterName)[unique(OsC_HM@meta.data$clusterName) %in% Obio@parameterList$clusterNameOrder ]

if (length(check) == length(unique(OsC_HM@meta.data$clusterName))){
  levels=Obio@parameterList$clusterNameOrder
} else {
  levels=sort(unique(OsCsel@meta.data$clusterName))
  Obio@parameterList$clusterNameOrder <- levels
}
OsCsel@meta.data$clusterName <- factor(
  OsCsel@meta.data$clusterName,
  levels=levels
)


OsCsel@meta.data <- OsCsel@meta.data[order(OsCsel@meta.data$clusterName,OsCsel@meta.data[[segmentationCol]]),]

if (packageVersion("Seurat") > "4.8.0"){
        dfData <- data.frame(OsCsel@assays$RNA$data)
    } else {
        dfData <- data.frame(OsCsel[["RNA"]]@data)
    }


dataMatrix <- data.matrix(dfData)
colnames(dataMatrix) <- gsub("\\.", "-", colnames(dataMatrix))
dfMeta <- OsCsel@meta.data

dataMatrix <- dataMatrix[,dfMeta[,selClust]]


###############################################################################
## Function to create heatmaps                                               ##

addHeatmap2List <- function(
    dataMatrix,
    geneGroupList,
    cluster_column_slices   = FALSE,
    cluster_columns         = TRUE,
    relativeExpression = FALSE,
    cmdVec = NULL,
    tag = NULL,
    showAllLegends = TRUE,
    figureCount = 1,
    chnkVec = NULL,
    plotList = NULL,
    maxNcharCatName = 10,
    dfMeta,
    group1ColorCol = "clusterColor",
    group1NameCol = "clusterName",
    group2ColorCol = "sampleColor",
    group2NameCol = "sampleName",
    columnSplitCol = "clusterName"
    ){

  if (is.null(chnkVec)){
    chnkVec <- as.vector(NULL, mode="character")
  }

  if (is.null(plotList)){
    plotList <- list()
  }

    allGenes <- unique(as.vector(unlist(geneGroupList)))


    if (is.null(cmdVec)){
      cmdVec <- as.vector(NULL, mode="character")
    }

    if (is.null(tag)){
      tag <- paste("Heatmap_", (length(plotList) + 1))
    }

    if (relativeExpression){
      legendString <- "log2 row mean"
    } else {
      legendString <- "lg10 Expr"
    }

# library("RColorBrewer")
# library("Seurat")
# library("ggplot2")
# library("viridis")
# #library("scMCA")
# library("circlize")
# library("ComplexHeatmap")



## Complex heatmap of cell/celltype correlations using just the top annotation per cell.  It's split by seurat cluster.
numbers_plot <- 1
# cors       <-  data.frame(OsC[["RNA"]]@data)
#cors_index <- apply(cors, 2, gettissue, numbers_plot)
#cors_index <- sort(unique(as.integer(cors_index)))
allGenes <- allGenes[allGenes %in% row.names(dataMatrix)]

heat.dat   <- dataMatrix[allGenes, ]
#heat.dat <- heat.dat
#heat.dat   <- t(apply(heat.dat,1,function(x){(x-mean(x))/sd(x)}))

# Comment out for absolute expression

heat.dat <- heat.dat[apply(heat.dat, 1, mean) != 0, ]

if (relativeExpression){
  heat.dat   <- t(apply(heat.dat,1,function(x){log2((x/mean(x)))}))
}

heat.dat[heat.dat == -Inf] <- 0

## make sure cat names aren't too long
nMax <- max(nchar(names(geneGroupList)))

if (nMax > maxNcharCatName){
  shortNames <- sapply(
    names(geneGroupList),
    function(x){
      substr(x, 1, maxNcharCatName)
    }
  )

  if (sum(duplicated(shortNames)) > 0){
    indexVec <- 1:length(shortNames)
    shortNames[duplicated(shortNames)] <- paste0(shortNames[duplicated(shortNames)],"_", indexVec[duplicated(shortNames)])
  }

  names(geneGroupList) <- shortNames

}



rowSplitVec <- row.names(heat.dat)
for (i in 1:length(geneGroupList)){
  rowSplitVec[rowSplitVec %in% geneGroupList[[i]]] <- names(geneGroupList)[i]
}



dfCol <- unique(dfMeta[,c(group1ColorCol, group1NameCol)])
colVec <- dfCol[,group1ColorCol]
names(colVec) <- dfCol[,group1NameCol]

dfCol2 <- unique(dfMeta[,c(group2ColorCol, group2NameCol)])
colVec2 <- dfCol2[,group2ColorCol]
names(colVec2) <- dfCol2[,group2NameCol]
#
# colList <- list(
#   dfCol,
#   dfCol2
# )


ht.anno <- ComplexHeatmap::HeatmapAnnotation(
    Type =  dfMeta[,group2NameCol],
    Cluster =  dfMeta[,group1NameCol],
    col = list(
        Type = colVec2,
        Cluster = colVec
    ),
    show_legend = showAllLegends
)


#bulkLogFC <- dfSel[allGenes, "contrast_2_logFC_p27NULL_E185OC_vs_WT_E185OC"]
#xcol <- ifelse(bulkLogFC < 0, "blue", "red")



#row_ha = rowAnnotation(Bulk = anno_barplot(bulkLogFC, gp = gpar(fill=xcol)),
#        show_legend = showAllLegends
#)

#lrow_ha = rowAnnotation(foo = anno_block(gp = gpar(fill = c("blue", "red")),
#        labels = c("Down", "Up"),
#        labels_gp = gpar(col = "white", fontsize = 10)),
#        show_legend = showAllLegends
#)
#     df = data.frame(
#         cluster = OsC_HM@meta.data$clusterName),
#     # col = list(
#     #     gp = gpar(col = "white")
#     # ),
#     annotation_legend_param = list(direction = "horizontal")
# )

if (relativeExpression){
  colRamp <- circlize::colorRamp2(c(-3, 0, 3),c("#3060cf", "#fffbbc","#c4463a"))
} else {
  colRamp <- circlize::colorRamp2(c(0, 6),c("#d3d3d3","#3060cf"))
}

if (nrow(heat.dat) > 100){
    rowFont <- 1
} else if (nrow(heat.dat) > 50){
    rowFont <- 1
} else if (nrow(heat.dat) > 25){
    rowFont <- 6
} else {
    rowFont <- 8
}

plotList[[tag]] <- ComplexHeatmap::Heatmap(
    heat.dat,
    row_split               = rowSplitVec,
    name                    = legendString,
    column_title_gp         = grid::gpar(fontsize = 6),
    row_title_rot           = 0, # Must be 0 or 90
    column_title_rot        = 90,
    column_split            = dfMeta[,columnSplitCol],
    #column_split            = column_split,
    cluster_column_slices   = cluster_column_slices,
    cluster_columns         = cluster_columns,
    cluster_rows            = TRUE,
    show_row_names          = TRUE,
    show_column_names       = FALSE,
    column_names_side       = "bottom",
    show_column_dend        = TRUE,
    row_dend_width          = grid::unit(20, "mm"),
    show_heatmap_legend     = showAllLegends,
    column_names_max_height = grid::unit(8, "cm"),
    row_names_gp            = grid::gpar(fontsize = 6),
    top_annotation          = ht.anno,
    #right_annotation = row_ha,
    #left_annotation = lrow_ha,
    #col                     = colorRamp2(c(-2, 0, 2),magma(3)),
    col                     = colRamp,
    column_names_rot        = 90,
    border = TRUE
)

  FNbase <- paste0(tag, VersionPdfExt)

  FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
  FNrel <- paste0("report_figures/", FNbase)

  pdf(FN)
    print(plotList[[tag]])
  dev.off()

  figLegend <- paste0(
    '**Figure ',
    figureCount,
    ':** ',
    'Heatmap split by cluster for gene set ',gsub("_", " ", tag),'. Download a pdf of this figure <a href="',FNrel,'" target="_blank">here</a>.'
  )

  figureCount <- figureCount + 1

  NewChnk <- paste0(
    "#### ", tag,
    "\n```{r hm_",
    tag,", results='asis', echo=F, eval=TRUE, warning=FALSE, fig.cap='",
    figLegend,"'}\n",
    "\n",
    "\n print(plotList[['",tag,"']])",
    "\n cat(  '\n')",
    "\n\n\n```\n"
)

  chnkVec <- c(
    chnkVec,
    NewChnk
  )

  returnList <- list(
    "plotList" = plotList,
    "chnkVec"  = chnkVec,
    "figureCount" = figureCount
  )

return(returnList)
}

## Done function to create heatmaps
###############################################################################


# for (i in 1:length(HMgeneSelections)){
#   for (j in 1:length(HMgeneSelections[[i]])){
#
#     tv <- HMgeneSelections[[i]][[j]]
#     tv <- tv[tv %in% row.names(OsC)]
#     ## Remove genes with all zero counts
#     tv <- tv[rowSums(OsC@assays$RNA[tv,]) != 0]
#     HMgeneSelections[[i]][[j]] <- tv
#   }
# }






# for (i in 1:length(HMgeneSelections)){
#   hl <- list(HMgeneSelections[[i]])
#   names(hl)[1] <- names(HMgeneSelections)[i]
#   geneList[[names(HMgeneSelections)[i]]]  <- hl
# }

#library(ComplexHeatmap)
plotList <- list()
chnkVec <- as.vector(NULL, mode="character")


## Make Heatmaps
if (!exists("figureCount")){
  figureCount <- 1
}


## Relative Heatmaps for all gene sets
for (i in 1:length(HMgeneSelections)){


  if (length(unlist(HMgeneSelections[[i]])) > 1){
    returnList <- addHeatmap2List(
        dataMatrix = dataMatrix,
        cluster_column_slices   = FALSE,
        cluster_columns         = FALSE,
        geneGroupList = HMgeneSelections[[i]],
        relativeExpression = TRUE,
        cmdVec = NULL,
        tag = paste0(names(HMgeneSelections)[i], "_Rel"),
        showAllLegends = TRUE,
        figureCount = figureCount,
        plotList = plotList,
        maxNcharCatName = 10,
        dfMeta = dfMeta,
        group1ColorCol = "clusterColor",
        group1NameCol = "clusterName",
        group2ColorCol = segmentationColorCol,
        group2NameCol = segmentationCol,
        chnkVec = chnkVec,
        columnSplitCol = "clusterName"

    )

    plotList <- returnList[["plotList"]]
    chnkVec <- returnList[["chnkVec"]]
    figureCount <- returnList[["figureCount"]]
  }
}

## Absolute
# for (i in 1:length(HMgeneSelections)){
#   if (length(unlist(HMgeneSelections[[i]])) > 1){
#     returnList <- addHeatmap2List(
#         dataMatrix = dataMatrix,
#         cluster_column_slices   = FALSE,
#         cluster_columns         = FALSE,
#         geneGroupList = HMgeneSelections[[i]],
#         relativeExpression = FALSE,
#         cmdVec = NULL,
#         tag = paste0(names(HMgeneSelections)[i], "_Abs"),
#         showAllLegends = TRUE,
#         figureCount = figureCount,
#         plotList = plotList,
#         maxNcharCatName = 10,
#         dfMeta = dfMeta,
#         group1ColorCol = "clusterColor",
#         group1NameCol = "clusterName",
#         group2ColorCol = segmentationColorCol,
#         group2NameCol = segmentationCol,
#         chnkVec = chnkVec,
#         columnSplitCol = "clusterName"
#
#     )
#
#     plotList <- returnList[["plotList"]]
#     chnkVec <- returnList[["chnkVec"]]
#     figureCount <- returnList[["figureCount"]]
#   }
# }





rm(OsC_HM)


## Done making Heatmap                                                       ##
###############################################################################


if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}

```


### Heatmaps - Relative Expression {`r tabVar`}

In this section heatmaps and dotplots for various gene categories are provided.

:::: {.panel-tabset .nav-pills}
```{r Cluster_overview, echo=TRUE, eval=TRUE, warning=FALSE, results="asis"}

cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))

```
::::

```{r process_heatmap_data_rel, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE, error=F}

plotList <- list()

chnkVec <- as.vector(NULL, mode="character")

if (!exists("figureCount")){
  figureCount <- 1
}


for (i in 1:length(HMgeneSelections)){

  # tag <- names(HMgeneSelections)[i]
  # tag <- unlist(strsplit(tag, "_LRT_"))[2]
  # tag <- unlist(strsplit(tag,"_Age_Group_pos"))[1]
  #
  # selCols <- colnames(dataMatrix)[grep(paste0(tag, "_"), colnames(dataMatrix))]
  # dataMatrix <- dataMatrix[,selCols]
  # dataMatrix <- dataMatrix[rowSums(dataMatrix) != 0, ]

  if (length(unlist(HMgeneSelections[[i]])) > 1){
    returnList <- addHeatmap2List(
        dataMatrix = dataMatrix,
        cluster_column_slices   = FALSE,
        cluster_columns         = FALSE,
        geneGroupList = HMgeneSelections[[i]],
        relativeExpression = FALSE,
        cmdVec = NULL,
        tag = paste0(names(HMgeneSelections)[i], "_Abs"),
        showAllLegends = TRUE,
        figureCount = figureCount,
        plotList = plotList,
        maxNcharCatName = 10,
        dfMeta = dfMeta,
        group1ColorCol = "clusterColor",
        group1NameCol = "clusterName",
        group2ColorCol = segmentationColorCol,
        group2NameCol = segmentationCol,
        chnkVec = chnkVec ,
        columnSplitCol = "clusterName"

    )

    plotList <- returnList[["plotList"]]
    chnkVec <- returnList[["chnkVec"]]
    figureCount <- returnList[["figureCount"]]
  }
}

# plotList <- addHeatmap2List(
#     OsC = OsC,
#     geneGroupList = geneGroupList,
#     relativeExpression = TRUE,
#     plotList = plotList,
#     cmdVec = NULL,
#     tag = "Channels_Rel",
#     showAllLegends = TRUE
#     )





if (length(plotList) > 3){
    tabVar <- ".tabset .tabset-fade .tabset-dropdown"
} else {
    tabVar <- ".tabset .tabset-fade .tabset-pills"
}

## To plot all heatmaps in one file
# FNbase <- paste0("Summary.heatmaps", VersionPdfExt)

#FN <- paste0(Obio@parameterList$reportFigDir, FNbase)
#FNrel <- paste0("report_figures/", FNbase)

#pdf(FN)
#    print(plotList)
#dev.off()


```


### Heatmaps - Absolute log10 Expression {`r tabVar`}
:::: {.panel-tabset .nav-pills}
```{r plot-heatmaps-rel, echo=T, eval=TRUE, warning=FALSE, results='asis'}
###############################################################################
## Do category enrichment on clusters                                        ##
cat(paste(knitr::knit(text = chnkVec, quiet = T), collapse = '\n'))
## Done doing enrichment on clusters                                         ##
###############################################################################

```
::::
```{r documentation_saving_1, eval=TRUE, echo=T, results=FALSE, message = FALSE, warning = FALSE, error = FALSE}

# source("save.biologic.robj.R")

print("Obio Object saved.")

# save(OsC,
#    file = paste0(
#         Obio@parameterList$localWorkDir,
#         Obio@parameterList$project_id,
#        ".Seurat.Robj"
#     )
#)

###############################################################################
## Rerunning of part C is required                                           ##

###############################################################################
## Create Excel output files                                                 ##

## Add ref-gene column ##
#dfTemp[["ref_gene"]] <- ""
#dfTemp[dfTemp$gene %in% refGenes, "ref_gene"] <- "+"

library(openxlsx)

dfTemp <- Obio@dataTableList[["DGE_table"]]

if (!dir.exists( paste0(
   Obio@parameterList$html_local,
   "report_tables/"))){
  dir.create(paste0(
   Obio@parameterList$html_local,
   "report_tables/"))
}

baseFN <- paste0(
   Obio@parameterList$project_id,
   ".DGE.table.single.xlsx"
)


outPutFN <- paste0(
     Obio@parameterList$html_local,
      "report_tables/",
     baseFN
)


FNrel <- paste0("report_table/", baseFN)

sheetName <- substr(paste0(Obio@parameterList$project_id, "_subcluster_DGE"),1,30)

wb <- createWorkbook()
    addWorksheet(wb, sheetName)
    freezePane(wb, sheetName ,  firstActiveRow = 2)

    ## Filter is inactivated, as it does not appear to be compatible with the current version of Excel
    #addFilter(wb, 1, row = 1, cols = 1:ncol(dfOutput))

## Style headers ##
hs1 <- createStyle(
  fontColour = "#ffffff",
  fgFill = "#000000",
  halign = "CENTER",
  textDecoration = "Bold"
)

writeData(wb, 1,dfTemp, startRow = 1, startCol = 1, headerStyle = hs1)

saveWorkbook(
  wb,
  outPutFN ,
  overwrite = TRUE
)

## Done creating Excel output files                                          ##
###############################################################################

###############################################################################
## Create cat enrichment table                                               ##

## Add ref-gene column ##
#dfTemp[["ref_gene"]] <- ""
#dfTemp[dfTemp$gene %in% refGenes, "ref_gene"] <- "+"

library(openxlsx)

## Enrichment result table is called dfResTable

if (!dir.exists( paste0(
   Obio@parameterList$html_local,
   "report_tables/"))){
  dir.create(paste0(
   Obio@parameterList$html_local,
   "report_tables/"))
}

baseFN <- paste0(
   Obio@parameterList$project_id,
   ".DGE.cat.enrichment.table2.xlsx"
)


outPutFN <- paste0(
     Obio@parameterList$html_local,
      "report_tables/",
     baseFN
)


FNrel <- paste0("report_table/", baseFN)

sheetName <- substr(paste0(Obio@parameterList$project_id, "_cat_enrichment_LRT"),1,30)

wb <- openxlsx::createWorkbook()
    openxlsx::addWorksheet(wb, sheetName)
    openxlsx::freezePane(wb, sheetName ,  firstActiveRow = 2)

    ## Filter is inactivated, as it does not appear to be compatible with the current version of Excel
    #addFilter(wb, 1, row = 1, cols = 1:ncol(dfOutput))

## Style headers ##
hs1 <- openxlsx::createStyle(
  fontColour = "#ffffff",
  fgFill = "#000000",
  halign = "CENTER",
  textDecoration = "Bold"
)

openxlsx::writeData(wb, 1,dfTemp, startRow = 1, startCol = 1, headerStyle = hs1)

saveWorkbook(
  wb,
  outPutFN ,
  overwrite = TRUE
)

## Done creating Excel output files                                          ##
###############################################################################

```


<!-- Optional 2: Add GSEA analysis -->
```{r child = 'DGE.M1.cat.enrichment.fGSEA.Rmd', eval=FALSE}
```


```{r, echo=F, eval=TRUE, warning=FALSE, results=F, error = TRUE}

# source("save.biologic.robj.R")

# print("Obio Object saved.")

# save(OsC,
#     file = paste0(
#          Obio@parameterList$localWorkDir,
#          Obio@parameterList$project_id,
#         ".Seurat.Robj"
#      )
# )


```




```{r create_report_params, eval=T, results="asis"}
documentationParams <- list(

    "title" = "Pseudobulk Differential Gene Expression Analysis",
    "subtitle" =  "",
    "abstract" = ""

)


## Try to retrieve project data from db ##
library(RMySQL)
db.pwd2 <- "_asf_"
db.user2 <- "asf"
host2 <- "ms1.thecrick.org"
projectParams <- documentationParams

tryCatch({
    dbDB = dbConnect(drv = RMySQL::MySQL(), user = db.user2, password = db.pwd2, host = host2, dbname = "asf");
dfProposal =  dbGetQuery(dbDB, paste0("SELECT * FROM asf_proposals WHERE project_name ='",Obio@parameterList$lims.id,"'"));
dbDisconnect(dbDB)
  }, error = function(x) {
    message("Project Database could not be reached or has no entry in Obio@parameterList$lims.id for this analysis.")

})

if (exists("dfProposal")){
  if (nrow(dfProposal) == 1){
      if (!is.na(dfProposal[1,"ProjectAlias"]) & dfProposal[1,"ProjectAlias"] != ""){
          projectParams[["title"]] = paste0(dfProposal[1,"ProjectAlias"], " - ", dfProposal[1,"project_name"])
      }

      if (!is.na(dfProposal[1,"project_user"]) & dfProposal[1,"project_user"] != ""){
          projectParams[["subtitle"]] = paste0(dfProposal[1,"user_lab"], " Lab - ", dfProposal[1,"project_user"])
          projectParams[["subtitle"]] <- gsub("^ Lab - ", "", projectParams[["subtitle"]])

      }

      if (!is.na(dfProposal[1,"proposal_text"]) & dfProposal[1,"proposal_text"] != ""){
          projectParams[["abstract"]] = dfProposal[1,"proposal_text"]


      }
  }
}

## Escape all special characters
projectParams <- lapply(
  projectParams, function(x)
  #gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\1", x)
  gsub("([.|()/\\^{}+$*?]|\\[|\\])", " ", x)
)

projectParams <- lapply(
  projectParams, function(x)
  #gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\1", x)
  gsub("\\\n", " ", x)
)


#projectParams$title <- "Title"
# projectParams$abstract <- "This is the QC section."
#projectParams$subtitle <- "Abstract"

```



## Documentation
```{r documentation, eval=TRUE, echo=T, results=T}
print(paste0("Analysisdirectory: ", getwd()))

biologic_active_object_dir <- paste0(
    Obio@parameterList$folder,
    "data/biologic_active_object/"
)

bFN <- paste0(
    biologic_active_object_dir,
    Obio@parameterList$project_id,
    ".bioLOGIC.Robj"
)
print(paste0("bioLOGIC data object: ", bFN))

sessionInfo()
```

```{r, eval=TRUE, echo=F, results=FALSE, message = FALSE, warning = FALSE}
tempDir <- "../../../../workdir/temp/"

if (!dir.exists(tempDir)){
  dir.create(tempDir, recursive = T)
}

FN <- "../../../../workdir/temp/temp.workspace.RData"
save.image(FN)
```